#!/usr/bin/env node
/**
 * Generates src/Config.js from config.json.
 * Run: node build.js  (or: npm run push)
 */

const fs   = require('fs');
const path = require('path');

const configPath = path.join(__dirname, 'config.json');
const outputPath = path.join(__dirname, 'src', 'Config.js');

if (!fs.existsSync(configPath)) {
  console.error(
    'Error: config.json not found.\n' +
    'Copy config.example.json to config.json and fill in your values:\n\n' +
    '  cp config.example.json config.json\n'
  );
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

// Validate required fields
const required = ['sourceFolderId', 'calendarId', 'pollIntervalMinutes', 'timeWindow', 'rules'];
required.forEach(function (key) {
  if (config[key] === undefined) {
    console.error('Error: missing required field "' + key + '" in config.json');
    process.exit(1);
  }
});

const allowedIntervals = [1, 5, 10, 15, 30];
if (!allowedIntervals.includes(config.pollIntervalMinutes)) {
  console.error(
    'Error: pollIntervalMinutes must be one of ' + allowedIntervals.join(', ') +
    '. Got: ' + config.pollIntervalMinutes
  );
  process.exit(1);
}

if (config.rules.length === 0) {
  console.warn('Warning: rules array is empty — no recordings will be moved.');
}

/**
 * Serializes an eventNamePattern:
 *   "/pattern/flags"  → RegExp literal (e.g. /client.*review/i)
 *   "plain string"    → quoted JS string
 */
function serializePattern(pattern) {
  const match = pattern.match(/^\/(.+)\/([gimsuy]*)$/);
  return match ? ('/' + match[1] + '/' + match[2]) : JSON.stringify(pattern);
}

const rulesCode = config.rules
  .map(function (rule) {
    return (
      '    {\n' +
      '      eventNamePattern: ' + serializePattern(rule.eventNamePattern) + ',\n' +
      '      destinationFolderId: ' + JSON.stringify(rule.destinationFolderId) + ',\n' +
      '    }'
    );
  })
  .join(',\n');

const output =
  '// AUTO-GENERATED by build.js — do not edit directly.\n' +
  '// Edit config.json and run: npm run build\n' +
  '\n' +
  '// eslint-disable-next-line no-unused-vars\n' +
  'const CONFIG = {\n' +
  '  sourceFolderId: ' + JSON.stringify(config.sourceFolderId) + ',\n' +
  '  calendarId: ' + JSON.stringify(config.calendarId) + ',\n' +
  '  calendarLookbackHours: ' + Number(config.calendarLookbackHours || 4) + ',\n' +
  '  pollIntervalMinutes: ' + Number(config.pollIntervalMinutes) + ',\n' +
  '  timeWindow: {\n' +
  '    startHour: ' + Number(config.timeWindow.startHour) + ',\n' +
  '    endHour: ' + Number(config.timeWindow.endHour) + ',\n' +
  '  },\n' +
  '  rules: [\n' +
  rulesCode + '\n' +
  '  ],\n' +
  '};\n';

fs.writeFileSync(outputPath, output);
console.log('✓ src/Config.js generated from config.json');

// Node.js compatibility — export pure functions for testing
if (require.main !== module) {
  module.exports = { serializePattern: serializePattern };
}
